version: '3.8'

services:
  # Base de Datos
  db:
    image: postgres:16
    container_name: tech_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: productivity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend
  backend:
    build: ./backend
    container_name: tech_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin_password
      DB_HOST: db        # Importante: Nombre del servicio de arriba
      DB_NAME: productivity_db
      GOOGLE_CREDENTIALS_FILE: /app/credentials/google_secret.json
    depends_on:
      - db

  # Frontend (Lo dejaremos listo, aunque ahora nos enfocamos en backend)
  frontend:
    build: ./frontend
    container_name: tech_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: